AllCops:
  Exclude:
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'db/**/*.rb'
    - 'config/**/*.rb'
    - 'bin/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
